/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-surface": "#191c1d",
        "surface": "#f8f9fa",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#4d44e3",
        "surface-bright": "#f8f9fa",
        "outline": "#777587",
        "on-primary": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-container": "#006172",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "primary-container": "#4f46e5",
        "on-error": "#ffffff",
        "surface-container-highest": "#e1e3e4",
        "on-surface-variant": "#464555",
        "on-background": "#191c1d",
        "tertiary-container": "#6f3dd9",
        "on-tertiary-fixed-variant": "#5516be",
        "secondary-fixed": "#acedff",
        "inverse-surface": "#2e3132",
        "surface-variant": "#e1e3e4",
        "primary-fixed-dim": "#c3c0ff",
        "tertiary-fixed-dim": "#d0bcff",
        "primary-fixed": "#e2dfff",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-container": "#e3d5ff",
        "tertiary": "#571ac0",
        "on-primary-fixed": "#0f0069",
        "on-error-container": "#93000a",
        "secondary": "#00687a",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#23005c",
        "on-secondary-fixed": "#001f26",
        "on-primary-container": "#dad7ff",
        "inverse-primary": "#c3c0ff",
        "surface-container-high": "#e7e8e9",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-on-surface": "#f0f1f2",
        "surface-dim": "#d9dadb",
        "primary": "#3525cd",
        "background": "#f8f9fa",
        "secondary-container": "#57dffe",
        "tertiary-fixed": "#e9ddff",
        "outline-variant": "#c7c4d8",
        "on-secondary-fixed-variant": "#004e5c"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "fontFamily": {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
